      # Step 1: Setup essential prerequisites ONCE for the entire job
      - name: Setup Prerequisites (Node, uv, Go, Deno)
        run: |
          echo "Setting up Node.js, uv, Go, Deno..."
          # CORRECTED: Removed 'timeout' from apt-get install
          sudo apt-get update && sudo apt-get install -y --no-install-recommends ca-certificates curl gnupg git
          # Node.js v20 (needed for mcp-inspector and some servers)
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
          echo "Node Version: $(node --version)"
          echo "NPM Version: $(npm --version)"
          # uv (for Python dependency management)
          curl -LsSf https://astral.sh/uv/install.sh | sh
          export PATH="$HOME/.cargo/bin:$PATH" # Add uv to PATH for this step and subsequent ones
          echo "uv Version: $(uv --version)"
          # Go (for Go-based servers)
          sudo add-apt-repository ppa:longsleep/golang-backports -y
          sudo apt-get update
          sudo apt-get install -y golang-go
          echo "Go Version: $(go version)"
          # Deno (for Deno-based servers like pydantic/mcp-run-python)
          curl -fsSL https://deno.land/install.sh | sh
          export DENO_INSTALL="$HOME/.deno"
          export PATH="$DENO_INSTALL/bin:$PATH" # Add deno to PATH
          echo "Deno Version: $(deno --version)"
          # Verify Docker client (Docker daemon runs on GitHub runners)
          docker --version
          # Verify timeout command exists (should be part of coreutils)
          command -v timeout
        # Make exports available to subsequent steps
        shell: bash -eo pipefail {0}
